### ISSUE TITLE
Update for compatibility with Craft 4

### ISSUE THREAD

**Issue by bencresty** [ethercreative/logs#13]
Hi,

Of the plugins we use this is the only plugin left in the Craft 4 upgrade tool showing it's not ready for Craft 4. Any chance the plugin will be made compatible with Craft 4 any time soon?

Thanks in advance!

**Comment by alexjcollins** [comment]
@bencresty Yep — we'll try and sort something over the next week or two. Cheers!

**Comment by bencresty** [comment]
@alexjcollins Thanks for the quick response. Nice to see!

**Comment by justinholtweb** [comment]
@alexjcollins any update on the Craft 4 compatible version?

**Comment by alexjcollins** [comment]
Hey @justinholtweb - shouldn't be much longer. We're planning on this week.
