### ISSUE TITLE
[Security] Directory traversal through URL manipulation

### ISSUE THREAD

**Issue by rob-c-baker** [ethercreative/logs#2]
When viewing the log screen at a URL like this:

https://example.com/admin/utilities/logs?log=web.log

It is possible to change the "log" parameter to view any readable file on the filesystem, like this:

https://example.com/admin/utilities/logs?log=../../.env

**Comment by rob-c-baker** [comment]
Suggest something like in `ether\logs\Utility` class, around line 45:

```php
$currentLog = basename($currentLog);
```

**Comment by Tam** [comment]
Should be fixed in the latest release, thanks for letting us know!
