### ISSUE TITLE
Latest Version Not Installing via Plugin Store

### ISSUE THREAD

**Issue by sm9** [ethercreative/logs#3]
I just installed Logs via the plugin store on Craft CMS 3.2.7, and noticed that it installed Logs 3.0.0 rather than the latest version (with the critical security update) of 3.0.1. I install plugins via the GUI in the control panel rather than using the command line so maybe this is my issue, but just mentioning this for info.

**Comment by Tam** [comment]
Whoops, forgot to actually release that update! Thanks for letting me know.
